### ISSUE TITLE
Slash off the one-off supervisor hack that we are most definitely not going to use again

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.portfolio.allocate#1]
Yes, I have thoughts on the supervisor process. Let's slash it. It was a one off hack for a workflow we are most definitely not going to use again.

_Originally posted by @jacobvjk in https://github.com/RMI-PACTA/pacta.portfolio.analysis/issues/248#issuecomment-1534139300_

**Comment by cjyetman** [comment]
I'm not sure what this issue means.

My interpretation is that `pacta.portfolio.analysis::get_ald_raw()` was changed to `pacta.portfolio.analysis::get_abcd_raw()` in https://github.com/RMI-PACTA/pacta.portfolio.analysis/pull/248, but @jacobvjk's comment suggests that we should revert that change?

**Comment by jacobvjk** [comment]
> I'm not sure what this issue means.
> 
> My interpretation is that `pacta.portfolio.analysis::get_ald_raw()` was changed to `pacta.portfolio.analysis::get_abcd_raw()` in [RMI-PACTA/pacta.portfolio.analysis#248](https://github.com/RMI-PACTA/pacta.portfolio.analysis/pull/248), but @jacobvjk's comment suggests that we should revert that change?

No, we do not need to revert to `get_ald_raw()`, we can keep `get_abcd_raw()`. I was just trying to say that the first `if` condition is not needed anymore. We can simply keep the `else` part of this control flow: https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/8147175a4705f909e02d3676c970371b7b0f8e65/R/get_abcd_raw.R#L13

The flag `supervisor_workflow` was introduced as a one off hack more than 1.5 years ago for one project and afaik has never been used again.
